// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import RequestController from "./request_controller.js"
application.register("request", RequestController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)